#include "vx_platform.h"

#include "vx_fs.h"
#include "vx_process.h"
#include "vx_limits.h"
#include "vx_util.h"

#include "sk_cmd_init.h"
#include "sk_cli.h"
#include "sk_util.h"
#include "sk_globals.h"
#include "sk_paths.h"

#include <stdio.h>

//----------------------------------------------------------------------------------------------------
// INIT

static const char *SK_DEF_STORMFILE = "// Stormfile, autogenerated by sk new\n\n"
                                      "cc: /usr/bin/clang\n"
                                      "cflags: -Wall -Wextra -Werror\n"
                                      "lflags: \n"
                                      "defines: -DDEBUG\n"
                                      "build_type: debug\n"
                                      "target storm\n"
                                      "{\n"
                                      "    if (build_type == debug)\n"
                                      "    {\n"
                                      "        cflags:: -g\n"
                                      "    }\n"
                                      "    else\n"
                                      "    {\n"
                                      "        cflags:: -O2\n"
                                      "    }\n\n"
                                      "    sources:\n"
                                      "        src/\n\n"
                                      "    includes: -Isrc\n"
                                      "}\n";

bool sk_meta_load(struct sk_meta *meta, const char *target_cc)
{
    if (meta == nullptr || target_cc == nullptr)
    {
        return false;
    }

    char full_meta_path[VX_PATH_MAX];
    snprintf(full_meta_path,
             sizeof(full_meta_path),
             "%s%s%s",
             g_sk_global_ctx.rpath,
             VX_PATH_SEP_STR,
             SK_PATH_STORM_META_FILE);

    vx_sv file = vx_fs_read(full_meta_path, sk_arena_alloc, g_sk_global_arena);

    if (file.data == nullptr)
    {
        return false;
    }

    char *cursor       = (char *) file.data;
    char *end          = cursor + file.len;
    bool  found_target = false;

    while (cursor < end)
    {
        char *line_end = strchr(cursor, CHAR_NEWLINE);

        if (line_end == nullptr)
        {
            line_end = end;
        }

        char *sep = strchr(cursor, CHAR_EQUAL);

        if (sep && sep < line_end)
        {
            size_t key_len = sep - cursor;
            char  *val     = sep + 1;
            size_t val_len = line_end - val;

            if (strncmp("cc_name", cursor, key_len) == 0)
            {
                if (strncmp(target_cc, val, val_len) == 0 && strlen(target_cc) == val_len)
                {
                    found_target = true;
                    snprintf(meta->cc_name, sizeof(meta->cc_name), "%.*s", (i32) val_len, val);
                }
                else
                {
                    found_target = false;
                }
            }
            else if (found_target)
            {
                if (strncmp("cc_path", cursor, key_len) == 0)
                {
                    snprintf(meta->cc_path, sizeof(meta->cc_path), "%.*s", (i32) val_len, val);
                }
                else if (strncmp("cc_ver", cursor, key_len) == 0)
                {
                    snprintf(meta->cc_ver, sizeof(meta->cc_ver), "%.*s", (i32) val_len, val);
                    return true;
                }
            }
        }

        cursor = (line_end == end) ? end : line_end + 1;
    }

    return found_target;
}

static const char *g_sk_compiler_canditates[] = {
    "clang",
    "gcc",
    "cl",
    "clang++",
    "g++",
    nullptr,
};

void sk_meta_init_cc(const char *cc_name, const char *rpath)
{
    cc_name = cc_name == nullptr ? "gcc" : cc_name;

    char resolved_path[VX_PATH_MAX];

    if (vx_fs_which(cc_name, resolved_path, sizeof(resolved_path)) != VX_OK)
    {
        return;
    }

    char meta_path[VX_PATH_MAX];
    snprintf(
        meta_path, sizeof(meta_path), "%s%s%s", rpath, VX_PATH_SEP_STR, SK_PATH_STORM_META_FILE);

    char tmp_buf[VX_PATH_MAX];
    snprintf(tmp_buf,
             sizeof(tmp_buf),
             "%s%s%s%s%s",
             rpath,
             VX_PATH_SEP_STR,
             SK_PATH_STORM_DIR,
             VX_PATH_SEP_STR,
             "tmp_ver");
    const char *tmp_ver_file = tmp_buf;

    char *argv[] = {resolved_path, "--version", nullptr};

    struct vx_proc_cfg cfg = {0};

    cfg.flags       = VX_PROCESS_FLAGS_SILENT;
    cfg.stdout_path = tmp_ver_file;

    struct vx_process proc = {0};

    if (vx_process_spawn(&proc, resolved_path, argv, &cfg) == VX_OK)
    {
        vx_process_wait(&proc);

        if (proc.exit_code == 0)
        {
            vx_sv ver_data = vx_fs_read(tmp_ver_file, sk_arena_alloc, g_sk_global_arena);

            if (ver_data.data)
            {
                char *newline = strchr(VX_CAST(char *, ver_data.data), CHAR_NEWLINE);
                if (newline)
                {
                    *newline = CHAR_NULTERM;
                }

                vx_fappend(meta_path,
                           "cc_name=%s\ncc_ver=%s\n\n",
                           resolved_path,
                           VX_CAST(char *, ver_data.data));

                vx_fs_rmrf(tmp_ver_file);
            }
        }
    }
}

static void create_storm_dir(const char *root, const char *subdir)
{
    if (root == nullptr || subdir == nullptr)
    {
        return;
    }

    char path[VX_PATH_MAX];
    snprintf(path, sizeof(path), "%s%s%s", root, VX_PATH_SEP_STR, subdir);

    if (vx_mkdir_p(path) != VX_OK)
    {
        VX_ASSERT_LOG("Failed to create: %s", path);
        return;
    }
    vx_dbglog("Created: %s", path);
}

void sk_cmd_init_fn(struct sk_ctx *ctx)
{
    const char *rpath = ctx->rpath;
    const bool  force = (ctx->active_opt & SK_OPT_FORCE);

    char stormfile[VX_PATH_MAX];
    snprintf(stormfile, sizeof(stormfile), "%s%s%s", rpath, VX_PATH_SEP_STR, SK_PATH_STORMFILE);

    if (sk_is_initialized_at(rpath) && !force)
    {
        vx_warn("Storm-Knell is initialized in: %s. Use --force to reset", rpath);
        return;
    }

    if (force)
    {
        char meta_path[VX_PATH_MAX];
        snprintf(meta_path, sizeof(meta_path), "%s/%s", rpath, SK_PATH_STORM_DIR);
        vx_fs_rmrf(meta_path);
        vx_fs_rmrf(stormfile);
    }

    create_storm_dir(rpath, SK_PATH_STORM_DIR);
    create_storm_dir(rpath, SK_PATH_STORM_DATA_DIR);
    create_storm_dir(rpath, SK_PATH_STORM_TRASH_DIR);
    create_storm_dir(rpath, SK_PATH_STORM_CACHE_DIR);

    if (vx_chdir(rpath) != VX_OK)
    {
        vx_errlog("Failed to enter directory: %s", rpath);
        return;
    }
    vx_dbglog("rpath: %s", rpath);

    if (vx_fwrite(stormfile, "%s", SK_DEF_STORMFILE) != VX_OK)
    {
        VX_ASSERT_LOG("Failed writing to file: %s", stormfile);
        return;
    }
    vx_dbglog("Created: %s", stormfile);

    char meta_path[VX_PATH_MAX];
    snprintf(
        meta_path, sizeof(meta_path), "%s%s%s", rpath, VX_PATH_SEP_STR, SK_PATH_STORM_META_FILE);

    vx_fwrite(meta_path, "# Storm-Knell Compiler Metadata\n\n");

    for (i32 i = 0; g_sk_compiler_canditates[i] != nullptr; i++)
    {
        sk_meta_init_cc(g_sk_compiler_canditates[i], rpath);
    }

    vx_log("Storm-Knell initialized in: %s", rpath);
}
