#include "sk_cmd_new.h"
#include "sk_cli.h"
#include "sk_util.h"
#include "sk_paths.h"

#include "vx_io.h"
#include "vx_fs.h"
#include "vx_util.h"

//----------------------------------------------------------------------------------------------------
// INIT

static const char *SK_DEF_STORMFILE = "#Stormfile, autogenerated by sk new\n\n"
                                      "cc: \"/usr/bin/clang\"\n"
                                      "cflags: [\"-Wall\", \"-Wextra\", \"-Werror\"]\n"
                                      "lflags: \n"
                                      "defines: [\"-DDEBUG\"]\n";

static void create_storm_dir(const char *root, const char *subdir)
{
    if (root == nullptr || subdir == nullptr)
    {
        return;
    }

    char path[VX_PATH_MAX];
    snprintf(path, sizeof(path), "%s%s%s", root, VX_PATH_SEP_STR, subdir);

    if (vx_mkdir_p(path) != VX_OK)
    {
        VX_ASSERT_LOG("Failed to create: %s", path);
        return;
    }
    vx_dbglog("Created: %s", path);
}

void sk_cmd_init_fn(struct sk_ctx *ctx)
{
    const char *rpath = ctx->rpath ? ctx->rpath : vx_getcwd_fn();
    const bool  force = (ctx->active_opt & SK_OPT_FORCE);

    char stormfile[VX_PATH_MAX];
    snprintf(stormfile, sizeof(stormfile), "%s%s%s", rpath, VX_PATH_SEP_STR, SK_PATH_STORMFILE);

    if (sk_is_initialized_at(rpath) && !force)
    {
        vx_warn("Storm-Knell is initialized in: %s. Use --force to reset", rpath);
        return;
    }

    if (force)
    {
        char meta_path[VX_PATH_MAX];
        snprintf(meta_path, sizeof(meta_path), "%s/%s", rpath, SK_PATH_STORM_DIR);
        vx_fs_rmrf(meta_path);
        vx_fs_rmrf(stormfile);
    }

    create_storm_dir(rpath, SK_PATH_STORM_DIR);
    create_storm_dir(rpath, SK_PATH_STORM_DATA_DIR);
    create_storm_dir(rpath, SK_PATH_STORM_TRASH_DIR);
    create_storm_dir(rpath, SK_PATH_STORM_CACHE_DIR);

    if (vx_fwrite(stormfile, "%s", SK_DEF_STORMFILE) != VX_OK)
    {
        VX_ASSERT_LOG("Failed writing to file: %s", stormfile);
        return;
    }
    vx_dbglog("Created: %s", stormfile);
    vx_log("Storm-Knell initialized in: %s", rpath);
}

//----------------------------------------------------------------------------------------------------
// PURGE

void sk_cmd_purge_fn(struct sk_ctx *ctx)
{
    if (ctx == nullptr)
    {
        return;
    }

    if (sk_resolve_project_root(ctx) != VX_OK)
    {
        vx_warn("Storm-Knell is not initialized here or in any parent directory.");
        return;
    }

    const char *target = ctx->init_dir;

    char stormfile[VX_PATH_MAX];
    snprintf(stormfile, sizeof(stormfile), "%s%s%s", target, VX_PATH_SEP_STR, SK_PATH_STORMFILE);
    vx_fs_rmrf(stormfile);

    char meta_path[VX_PATH_MAX];
    snprintf(meta_path, sizeof(meta_path), "%s/%s", target, SK_PATH_STORM_DIR);
    vx_fs_rmrf(meta_path);

    vx_log("Storm-Knell purged for: %s", target);
}

//----------------------------------------------------------------------------------------------------

vx_status sk_cmd_new_file(struct sk_ctx *ctx, const char *path)
{
    if (ctx == nullptr || path == nullptr)
    {
        return VX_ERROR;
    }

    return VX_OK;
}
