#include "vx_platform.h"
#include "vx_fs.h"
#include "vx_process.h"
#include "vx_limits.h"
#include "vx_util.h"

#include "sk_cmd_config.h"
#include "sk_cmd_init.h"
#include "sk_cmd_cache.h"
#include "sk_cli.h"
#include "sk_util.h"
#include "sk_globals.h"
#include "sk_paths.h"

#include <stdio.h>

//----------------------------------------------------------------------------------------------------

static void
sk_meta_write_cc_entry(const char *resolved_path, const char *short_name, const char *rpath);

//----------------------------------------------------------------------------------------------------
// INIT

static const char *g_sk_template_stormfile = "// Stormfile, autogenerated by sk init\n"
                                             "\n"
                                             "cc: /usr/bin/gcc\n"
                                             "cflags: -Wall -Wextra -Werror\n"
                                             "lflags:\n"
                                             "defines: -DDEBUG\n"
                                             "\n"
                                             "build_type: debug\n"
                                             "\n"
                                             "target sk_tmp\n"
                                             "{\n"
                                             "    print: __sk_version__\n"
                                             "    out: sk_tmp\n"
                                             "    kind: exec\n"
                                             "\n"
                                             "   if(build_type == debug){\n"
                                             "       cflags::  -g\n"
                                             "       defines:: -DDEBUG\n"
                                             "   }\n"
                                             "   else\n"
                                             "   {\n"
                                             "       cflags::  -O2\n"
                                             "       defines:: -DNDEBUG\n"
                                             "   }\n"
                                             "\n"
                                             "   sources: .\n"
                                             "\n"
                                             "   includes: -I.\n"
                                             "}\n";

bool sk_meta_load(struct sk_meta *meta, const char *target_cc)
{
    if (meta == nullptr || target_cc == nullptr)
    {
        return false;
    }

    char *full_meta_path =
        sk_path_join(g_sk_global_arena, g_sk_global_ctx.rpath, SK_PATH_STORM_META_FILE);

    vx_sv file = vx_fs_read(full_meta_path, sk_arena_alloc, g_sk_global_arena);
    if (file.data == nullptr)
    {
        return false;
    }

    char *cursor       = (char *) file.data;
    char *end          = cursor + file.len;
    bool  found_target = false;

    while (cursor < end)
    {
        char *line_end = strchr(cursor, CHAR_NEWLINE);
        if (line_end == nullptr)
        {
            line_end = end;
        }

        char *sep = strchr(cursor, CHAR_EQUAL);
        if (sep && sep < line_end)
        {
            size_t key_len = sep - cursor;
            char  *val     = sep + 1;
            size_t val_len = line_end - val;

            if (strncmp("cc_name", cursor, key_len) == 0)
            {
                if (strncmp(target_cc, val, val_len) == 0 && strlen(target_cc) == val_len)
                {
                    found_target = true;
                    snprintf(meta->cc_name, sizeof(meta->cc_name), "%.*s", (i32) val_len, val);

                    const char *ar_name = strstr(meta->cc_name, "clang") ? "llvm-ar" : "ar";

                    if (vx_fs_which(ar_name, meta->ar_path, sizeof(meta->ar_path)) != VX_OK ||
                        meta->ar_path[0] == CHAR_NULTERM)
                    {
                        snprintf(meta->ar_path, sizeof(meta->ar_path), "%s", ar_name);
                    }
                }
                else
                {
                    found_target = false;
                }
            }
            else if (found_target)
            {
                if (strncmp("cc_ver", cursor, key_len) == 0)
                {
                    snprintf(meta->cc_ver, sizeof(meta->cc_ver), "%.*s", (i32) val_len, val);
                    return true;
                }
            }
        }

        cursor = (line_end == end) ? end : line_end + 1;
    }

    return found_target;
}

void sk_meta_init_cc(const char *cc_name, const char *rpath)
{
    cc_name = cc_name != nullptr ? cc_name : "gcc";

    char resolved_path[VX_PATH_MAX];

    if (vx_fs_which(cc_name, resolved_path, sizeof(resolved_path)) != VX_OK)
    {
        return;
    }

    sk_meta_write_cc_entry(resolved_path, cc_name, rpath);
}

static void create_storm_dir(const char *root, const char *subdir)
{
    if (root == nullptr || subdir == nullptr)
    {
        return;
    }

    char *path = sk_path_join(g_sk_global_arena, root, subdir);

    if (vx_mkdir_p(path) != VX_OK)
    {
        VX_ASSERT_LOG("Failed to create: %s", path);
        return;
    }

    if (g_sk_global_ctx.active_opt & SK_OPT_VERBOSE)
    {
        vx_log("Created: %s", path);
    }
}

static void init_from_config(const char *rpath)
{
    const char *conf_dir = vx_platform_get_config_dir();

    char *conf_path =
        sk_path_join(g_sk_global_arena, conf_dir, SK_PATH_STORM_KNELL_COMPILER_CONF_FILE);

    if (!vx_isfile(conf_path))
    {
        static const char *defaults[] = {"gcc", "g++", "clang", "clang++", nullptr};
        for (i32 i = 0; defaults[i] != nullptr; i++)
        {
            char resolved[VX_PATH_MAX];
            if (vx_fs_which(defaults[i], resolved, sizeof(resolved)) == VX_OK)
            {
                sk_config_add_cc_path(resolved);
            }
        }
    }

    char *meta_path = sk_path_join(g_sk_global_arena, rpath, SK_PATH_STORM_META_FILE);
    vx_fwrite(meta_path, "# Storm-Knell Compiler Metadata\n\n");

    FILE *f = fopen(conf_path, "r");
    if (f == nullptr)
    {
        return;
    }

    char line[VX_PATH_MAX];
    while (fgets(line, sizeof(line), f))
    {
        line[strcspn(line, "\n")] = CHAR_NULTERM;
        if (line[0] == CHAR_NULTERM || line[0] == CHAR_HASH)
        {
            continue;
        }
        const char *short_name = strrchr(line, VX_PATH_SEP);

        short_name = short_name ? short_name + 1 : line;
        sk_meta_write_cc_entry(line, short_name, rpath);
    }
    fclose(f);
}

void sk_cmd_init_fn(struct sk_ctx *ctx)
{
    const char *rpath = ctx->rpath ? ctx->rpath : vx_getcwd_fn();
    const bool  force = (ctx->active_opt & SK_OPT_FORCE);

    if (sk_is_initialized_at(rpath) && !force)
    {
        vx_warn("Storm-Knell is initialized in: %s. Use --force to reset", rpath);
        return;
    }

    char *stormfile = sk_path_join(g_sk_global_arena, rpath, SK_PATH_STORMFILE);

    if (force)
    {
        char *meta_path = sk_path_join(g_sk_global_arena, rpath, SK_PATH_STORM_DIR);
        vx_fs_rmrf(meta_path);
    }

    create_storm_dir(rpath, SK_PATH_STORM_DIR);
    create_storm_dir(rpath, SK_PATH_STORM_DATA_DIR);
    create_storm_dir(rpath, SK_PATH_STORM_TRASH_DIR);
    create_storm_dir(rpath, SK_PATH_STORM_CACHE_DIR);

    if (vx_chdir(rpath) != VX_OK)
    {
        vx_errlog("Failed to enter directory: %s", rpath);
        return;
    }
    vx_dbglog("rpath: %s", rpath);

    if (!vx_isfile(stormfile))
    {
        if (vx_fwrite(stormfile, "%s", g_sk_template_stormfile) != VX_OK)
        {
            VX_ASSERT_LOG("Failed writing to file: %s", stormfile);
            return;
        }
        vx_dbglog("Created: %s", stormfile);
    }

    init_from_config(rpath);

    vx_log("Storm-Knell initialized in: %s", rpath);
}

void sk_meta_init_git(char *git_branch_out, char *git_hash_out, size_t max_len)
{
    snprintf(git_branch_out, max_len, "unknown");
    snprintf(git_hash_out, max_len, "unknown");

    vx_sv head_data = {0};
    if (vx_fs_exists(".git/HEAD"))
    {
        head_data = vx_fs_read(".git/HEAD", sk_arena_alloc, g_sk_global_arena);
        if (head_data.data == nullptr || head_data.len == 0)
        {
            return;
        }
    }

    char  *head_str = (char *) head_data.data;
    size_t head_len = head_data.len;

    while (head_len > 0 &&
           (head_str[head_len - 1] == CHAR_NEWLINE || head_str[head_len - 1] == CHAR_CARRIAGE ||
            head_str[head_len - 1] == CHAR_SPACE))
    {
        head_str[head_len - 1] = CHAR_NULTERM;
        head_len--;
    }

    const char *ref_prefix = "ref: ";

    size_t ref_prefix_len = 5;

    if (head_len > ref_prefix_len && strncmp(head_str, ref_prefix, ref_prefix_len) == 0)
    {
        char *ref_path = head_str + ref_prefix_len;

        const char *heads_dir   = "refs/heads/";
        char       *branch_name = strstr(ref_path, heads_dir);

        if (branch_name)
        {
            snprintf(git_branch_out, max_len, "%s", branch_name + strlen(heads_dir));
        }
        else
        {
            snprintf(git_branch_out, max_len, "%s", ref_path);
        }

        char *full_ref_path = sk_path_join(g_sk_global_arena, ".git", ref_path);

        vx_sv hash_data = vx_fs_read(full_ref_path, sk_arena_alloc, g_sk_global_arena);
        if (hash_data.data && hash_data.len >= 7)
        {
            char  *hash_str = (char *) hash_data.data;
            size_t hash_len = hash_data.len;
            while (hash_len > 0 &&
                   (hash_str[hash_len - 1] == '\n' || hash_str[hash_len - 1] == '\r' ||
                    hash_str[hash_len - 1] == ' '))
            {
                hash_str[hash_len - 1] = '\0';
                hash_len--;
            }
            snprintf(git_hash_out, max_len, "%s", hash_str);
        }
    }
    else if (head_len >= 7)
    {
        snprintf(git_branch_out, max_len, "DETACHED");
        snprintf(git_hash_out, max_len, "%s", head_str);
    }
}

static void
sk_meta_write_cc_entry(const char *resolved_path, const char *short_name, const char *rpath)
{
    char *meta_path = sk_path_join(g_sk_global_arena, rpath, SK_PATH_STORM_META_FILE);

    char tmp_buf[VX_PATH_MAX];
    snprintf(tmp_buf,
             sizeof(tmp_buf),
             "%s%s%s%s%s_%s",
             rpath,
             VX_PATH_SEP_STR,
             SK_PATH_STORM_DIR,
             VX_PATH_SEP_STR,
             "tmp_ver",
             short_name);
    const char *tmp_ver_file = tmp_buf;

    char *argv[] = {VX_CAST(char *, resolved_path), "--version", nullptr};

    struct vx_proc_cfg cfg = {0};

    cfg.flags       = VX_PROCESS_FLAGS_SILENT;
    cfg.stdout_path = tmp_ver_file;

    struct vx_process proc = {0};

    if (vx_process_spawn(&proc, resolved_path, argv, &cfg) == VX_OK)
    {
        vx_process_wait(&proc);
        vx_dbglog("exit_code: %d", proc.exit_code);

        if (proc.exit_code == 0)
        {
            vx_sv ver_data = vx_fs_read(tmp_ver_file, sk_arena_alloc, g_sk_global_arena);

            if (ver_data.data)
            {
                char *newline = strchr(VX_CAST(char *, ver_data.data), CHAR_NEWLINE);
                if (newline)
                {
                    *newline = CHAR_NULTERM;
                }

                vx_fappend(meta_path,
                           "cc_name=%s\ncc_ver=%s\n\n",
                           resolved_path,
                           VX_CAST(char *, ver_data.data));
            }
        }

        vx_fs_rmrf(tmp_ver_file);
    }
}
