// Auto-generated by Storm-Knell. Do not edit.
#pragma once
#define SK_VERSION_MAJOR 0
#define SK_VERSION_MINOR 9
#define SK_VERSION_PATCH 0
#define SK_VERSION_STRING "0.9.0"
#define SK_COMPILED_GCC 1
#define SK_COMPILED_CLANG 0
